url: https://dac-of-purdue.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Digital Agricultural Club of Purdue # the name of your site, e.g. ACME Corp.
